In [120]:
import numpy as np
from scipy.special import expit as sigmoid
from scipy.special import softmax as sm
import pandas as pd
import math
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss
from math import sqrt
from math import log

class NeuralNet:
    def __init__(self, num_features, num_hidden1,num_hidden2,num_hidden3,num_hidden4,num_hidden5,num_hidden6 ,alpha, max_epochs, num_output, _EPSILON):
        super().__init__()
        self.num_features=num_features  # number of input nodes (features)
        self.num_hidden1=num_hidden1  # number of hidden nodes for 1st hidden layer
        self.num_hidden2=num_hidden2  # number of hidden nodes for 2nd hidden layer
        self.num_hidden3=num_hidden3  # number of hidden nodes for 3rd hidden layer
        self.num_hidden4=num_hidden4  # number of hidden nodes for 4th hidden layer
        self.num_hidden5=num_hidden5  # number of hidden nodes for 5th hidden layer
        self.num_hidden6=num_hidden6  # number of hidden nodes for 6th hidden layer
        self.alpha=alpha  # learning rate
        self.max_epochs=max_epochs # maximum number of epochs
        self.num_output=num_output # number of output nodes
        self._EPSILON=_EPSILON
        self.loss = [] #list to store losses per 100 epochs 
        self.Weights_Input_to_H1=np.random.randn(self.num_hidden1, self.num_features)*(2/sqrt(self.num_features))
        self.Bias_Input_to_H1=np.zeros([self.num_hidden1,1])
        self.Weights_H1_to_H2=np.random.randn(self.num_hidden2, self.num_hidden1)*(2/sqrt(self.num_hidden1))
        self.Bias_H1_to_H2=np.zeros([self.num_hidden2,1])
        self.Weights_H2_to_H3=np.random.randn(self.num_hidden3, self.num_hidden2)*(2/sqrt(self.num_hidden2))
        self.Bias_H2_to_H3=np.zeros([self.num_hidden3,1])
        self.Weights_H3_to_H4=np.random.randn(self.num_hidden4, self.num_hidden3)*(2/sqrt(self.num_hidden3))
        self.Bias_H3_to_H4=np.zeros([self.num_hidden4,1])
        self.Weights_H4_to_H5=np.random.randn(self.num_hidden5, self.num_hidden4)*(2/sqrt(self.num_hidden4))
        self.Bias_H4_to_H5=np.zeros([self.num_hidden5,1])
        self.Weights_H5_to_H6=np.random.randn(self.num_hidden6, self.num_hidden5)*(2/sqrt(self.num_hidden5))
        self.Bias_H5_to_H6=np.zeros([self.num_hidden6,1])
        self.Weights_H6_to_output=np.random.randn(self.num_output, self.num_hidden6)*(2/sqrt(self.num_hidden6))
        self.Bias_H6_to_output=np.zeros([self.num_output,1])
        self.dWeights_Input_to_H1=np.zeros([self.num_hidden1, self.num_features])
        self.dBias_Input_to_H1=np.zeros([self.num_hidden1,1])
        self.dWeights_H1_to_H2=np.zeros([self.num_hidden2, self.num_hidden1])
        self.dBias_H1_to_H2=np.zeros([self.num_hidden2,1])
        self.dWeights_H2_to_H3=np.zeros([self.num_hidden3, self.num_hidden2])
        self.dBias_H2_to_H3=np.zeros([self.num_hidden3,1])
        self.dWeights_H3_to_H4=np.zeros([self.num_hidden4, self.num_hidden3])
        self.dBias_H3_to_H4=np.zeros([self.num_hidden4,1])
        self.dWeights_H4_to_H5=np.zeros([self.num_hidden5, self.num_hidden4])
        self.dBias_H4_to_H5=np.zeros([self.num_hidden5,1])
        self.dWeights_H5_to_H6=np.zeros([self.num_hidden6, self.num_hidden5])
        self.dBias_H5_to_H6=np.zeros([self.num_hidden6,1])
        self.dWeights_H6_to_output=np.zeros([self.num_output, self.num_hidden6])
        self.dBias_H6_to_output=np.zeros([self.num_output,1])
        
        

        
    
    def relU(self,X):
        return np.maximum(X, 0)
    
    def deriv(self,X):
        X[X>=0]=1
        X[X<0]=0
        
        return X
        
        
        
    def Softmax_grad(self,X):
        return(sm(X,axis=1)*(1-sm(X,axis=1)))
    
    def sigmoid(self,X):
        return 1/(1+np.exp(-X))
    
    def softmax(self,x):
        e=np.exp(x)
        for i in range(e.shape[1]):
            e[:,i]=e[:,i]/np.sum(e[:,i])
        return e
    
    def derivtanh(self,X):
        return 1-((np.tanh(X))**2)
    
    def categorical_cross_entropy(self,actual, predicted):
        sum_score = 0.0
        for i in range(len(actual)):
            for j in range(len(actual[i])):
                sum_score += actual[i][j] * log(self._EPSILON + predicted[i][j])
        mean_sum_score = 1.0 / len(actual) * sum_score
        return -mean_sum_score
                
            
            
        
    
    
        
    
 
        
    
    
        
        
    
        
    # TODO: complete implementation for forward pass
    def forward(self, X):
        self.z1=np.dot((self.Weights_Input_to_H1),(X))+self.Bias_Input_to_H1
        self.a1=self.relU(self.z1)
        self.z2=np.dot((self.Weights_H1_to_H2),(self.a1))+self.Bias_H1_to_H2
        self.a2=self.relU(self.z2)
        self.z3=np.dot((self.Weights_H2_to_H3),(self.a2))+self.Bias_H2_to_H3
        self.a3=self.relU(self.z3)
        self.z4=np.dot((self.Weights_H3_to_H4),(self.a3))+self.Bias_H3_to_H4
        self.a4=self.relU(self.z4)
        self.z5=np.dot((self.Weights_H4_to_H5),(self.a4))+self.Bias_H4_to_H5
        self.a5=self.relU(self.z5)
        self.z6=np.dot((self.Weights_H5_to_H6),(self.a5))+self.Bias_H5_to_H6
        self.a6=self.relU(self.z6)
        self.z7=np.dot((self.Weights_H6_to_output),(self.a6))+self.Bias_H6_to_output
        self.a7=self.softmax((self.z7))
        return self.a7
        
        
        
    
    # TODO: complete implementation for backpropagation
    # the following Numpy functions may be useful: np.dot, np.sum, np.tanh, numpy.ndarray.T
    def backprop(self, X, t):
            
        self.dWeights_Input_to_H1=np.zeros([self.num_hidden1, self.num_features])
        self.dBias_Input_to_H1=np.zeros([self.num_hidden1,1])
        self.dWeights_H1_to_H2=np.zeros([self.num_hidden2, self.num_hidden1])
        self.dBias_H1_to_H2=np.zeros([self.num_hidden2,1])
        self.dWeights_H2_to_H3=np.zeros([self.num_hidden3, self.num_hidden2])
        self.dBias_H2_to_H3=np.zeros([self.num_hidden3,1])
        self.dWeights_H3_to_H4=np.zeros([self.num_hidden4, self.num_hidden3])
        self.dBias_H3_to_H4=np.zeros([self.num_hidden4,1])
        self.dWeights_H4_to_H5=np.zeros([self.num_hidden5, self.num_hidden4])
        self.dBias_H4_to_H5=np.zeros([self.num_hidden5,1])
        self.dWeights_H5_to_H6=np.zeros([self.num_hidden6, self.num_hidden5])
        self.dBias_H5_to_H6=np.zeros([self.num_hidden6,1])
        self.dWeights_H6_to_output=np.zeros([self.num_output, self.num_hidden6])
        self.dBias_H6_to_output=np.zeros([self.num_output,1])
        self.dz7=(self.a7.reshape(self.num_output,-1)-t.reshape(self.num_output,-1))
        self.dBias_H6_to_output=np.sum(self.dz7,axis=1,keepdims=True)/(X.shape[1])
        self.dWeights_H6_to_output=np.dot((self.dz7),self.a6.T)/(X.shape[1])
        self.dz6=(np.dot(self.Weights_H6_to_output.T,self.dz7)) * (self.deriv(self.z6))
        self.dBias_H5_to_H6=np.sum(self.dz6,axis=1,keepdims=True)/(X.shape[1])
        self.dWeights_H5_to_H6=np.dot((self.dz6),(self.a5.T))/(X.shape[1])
        self.dz5=(np.dot(self.Weights_H5_to_H6.T,self.dz6)) * (self.deriv(self.z5))
        self.dBias_H4_to_H5=np.sum(self.dz5,axis=1,keepdims=True)/(X.shape[1])
        self.dWeights_H4_to_H5=np.dot((self.dz5),(self.a4.T))/(X.shape[1])
        self.dz4=(np.dot(self.Weights_H4_to_H5.T,self.dz5)) * (self.deriv(self.z4))
        self.dBias_H3_to_H4=np.sum(self.dz4,axis=1,keepdims=True)/(X.shape[1])
        self.dWeights_H3_to_H4=np.dot((self.dz4),(self.a3.T))/(X.shape[1])
        self.dz3=(np.dot(self.Weights_H3_to_H4.T,self.dz4)) * (self.deriv(self.z3))
        self.dBias_H2_to_H3=np.sum(self.dz3,axis=1,keepdims=True)/(X.shape[1])
        self.dWeights_H2_to_H3=np.dot((self.dz3),(self.a2.T))/(X.shape[1])
        self.dz2=(np.dot(self.Weights_H2_to_H3.T,self.dz3)) * (self.deriv(self.z2))
        self.dBias_H1_to_H2=np.sum(self.dz2,axis=1,keepdims=True)/(X.shape[1])
        self.dWeights_H1_to_H2=np.dot((self.dz2),(self.a1.T))/(X.shape[1])
        self.dz1=(np.dot(self.Weights_H1_to_H2.T,self.dz2)) * (self.deriv(self.z1))
        self.dBias_Input_to_H1=np.sum(self.dz1,axis=1,keepdims=True)/(X.shape[1])
        self.dWeights_Input_to_H1=np.dot((self.dz1),X.T)/(X.shape[1])
        
        
        
        
        
            
                
                
                
              
                        
                
      
        
        
    
    #TODO: complete implementation for fitting data, and change the existing code if needed
    def fit(self, x_train_data, y_train_data,x_dev_data,y_dev_data):
       
        
        
        for step in range(self.max_epochs):
            self.forward(x_train_data)
            self.backprop(x_train_data, y_train_data)
            #self.MSE=np.mean((self.dz7/2)**2)
            self.CCloss=self.categorical_cross_entropy(y_train_data,self.a7)
            #self.CCloss=np.mean(log_loss(y_true=y_train_data,y_pred=self.a7,normalize=True))
            self.Bias_H6_to_output=self.Bias_H6_to_output-((self.alpha)*(self.dBias_H6_to_output))
            self.Weights_H6_to_output=self.Weights_H6_to_output-((self.alpha)*(self.dWeights_H6_to_output))
            self.Bias_H5_to_H6=self.Bias_H5_to_H6-((self.alpha)*(self.dBias_H5_to_H6))
            self.Weights_H5_to_H6=self.Weights_H5_to_H6-((self.alpha)*(self.dWeights_H5_to_H6))
            self.Bias_H4_to_H5=self.Bias_H4_to_H5-((self.alpha)*(self.dBias_H4_to_H5))
            self.Weights_H4_to_H5=self.Weights_H4_to_H5-((self.alpha)*(self.dWeights_H4_to_H5))
            self.Bias_H3_to_H4=self.Bias_H3_to_H4-((self.alpha)*(self.dBias_H3_to_H4))
            self.Weights_H3_to_H4=self.Weights_H3_to_H4-((self.alpha)*(self.dWeights_H3_to_H4))
            self.Bias_H2_to_H3=self.Bias_H2_to_H3-((self.alpha)*(self.dBias_H2_to_H3))
            self.Weights_H2_to_H3=self.Weights_H2_to_H3-((self.alpha)*(self.dWeights_H2_to_H3))
            self.Bias_H1_to_H2=self.Bias_H1_to_H2-((self.alpha)*(self.dBias_H1_to_H2))
            self.Weights_H1_to_H2=self.Weights_H1_to_H2-((self.alpha)*(self.dWeights_H1_to_H2))
            self.Bias_Input_to_H1=self.Bias_Input_to_H1-((self.alpha)*(self.dBias_Input_to_H1))
            self.Weights_Input_to_H1=self.Weights_Input_to_H1-((self.alpha)*(self.dWeights_Input_to_H1))


            if step % 100 == 0:
                print(f'step: {step},  loss: {self.CCloss:3.150f}') 
                print(accuracy_score(np.argmax(y_train_data,axis=0),np.argmax(self.a7,axis=0)))
                print(accuracy_score(np.argmax(y_dev_data,axis=0),np.argmax(self.forward(x_dev_data),axis=0)))
                self.loss.append(self.CCloss)
                
           
        

        
                
        
    
    def predict(self,X,y=None):
        self.forward(X)
        if(self.num_output>1):
            self.a7=np.argmax(self.a7, axis=1)
        lin_out1=self.a7
        #y_hat=np.where(lin_out1>0.5,1,0)
        
            
        
        return lin_out1
            

   

In [3]:
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

# import some data to play with
iris = datasets.load_iris()
X = iris.data # we only take the first two features.
y = iris.target

#X=X[:, :]
#y=y[:]
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.1)


In [4]:
X_train, X_dev, Y_train, Y_dev = train_test_split(X_train, Y_train, test_size=0.11)
print(X_train)
print(Y_train)

[[6.9 3.1 5.1 2.3]
 [5.5 3.5 1.3 0.2]
 [6.7 2.5 5.8 1.8]
 [4.8 3.4 1.6 0.2]
 [5.1 3.8 1.5 0.3]
 [7.7 2.8 6.7 2. ]
 [5.1 2.5 3.  1.1]
 [6.2 3.4 5.4 2.3]
 [5.7 2.6 3.5 1. ]
 [6.  2.9 4.5 1.5]
 [5.7 4.4 1.5 0.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 3.9 1.2]
 [6.7 3.3 5.7 2.1]
 [4.9 3.  1.4 0.2]
 [5.2 3.4 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [6.5 2.8 4.6 1.5]
 [6.5 3.  5.2 2. ]
 [4.8 3.  1.4 0.1]
 [6.  2.2 4.  1. ]
 [6.  2.2 5.  1.5]
 [6.2 2.2 4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [5.  3.4 1.6 0.4]
 [7.2 3.  5.8 1.6]
 [5.4 3.9 1.3 0.4]
 [6.7 3.1 5.6 2.4]
 [6.2 2.8 4.8 1.8]
 [5.1 3.3 1.7 0.5]
 [6.3 2.9 5.6 1.8]
 [5.1 3.8 1.9 0.4]
 [6.3 2.5 4.9 1.5]
 [5.1 3.4 1.5 0.2]
 [6.3 2.7 4.9 1.8]
 [6.6 2.9 4.6 1.3]
 [6.7 3.  5.  1.7]
 [4.8 3.4 1.9 0.2]
 [5.9 3.  4.2 1.5]
 [5.4 3.4 1.7 0.2]
 [6.7 3.1 4.4 1.4]
 [6.4 3.2 4.5 1.5]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.3 0.3]
 [5.4 3.4 1.5 0.4]
 [7.7 3.8 6.7 2.2]
 [5.7 2.8 4.5 1.3]
 [5.2 2.7 3.9 1.4]
 [6.  3.4 4.5 1.6]
 [4.6 3.2 1.4 0.2]
 [5.5 4.2 1.

In [ ]:
import numpy as np
import pandas as pd

df_original = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data",
    header=None)
dataset = df_original.values

from sklearn.model_selection import train_test_split



In [2]:
import numpy as np
import pandas as pd

df_original = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data",
    header=None)
dataset = df_original.values

from sklearn.model_selection import train_test_split

X = dataset[:, 0:60].astype(float)
Y = dataset[:, 60]
# convert string labels to binary
Y[Y == 'R'] = 0
Y[Y == 'M'] = 1
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [48]:
import sklearn
X,Y=sklearn.datasets.load_breast_cancer(return_X_y=True, as_frame=False)

In [26]:
dataset_noheader=np.delete(dataset,0,0)

In [27]:
dataset_noheader[:,0]

array(['1', '1', '1', ..., 3, 3, 3], dtype=object)

In [28]:
X = dataset_noheader[:, 0:4].astype(float)
Y = dataset_noheader[:, 0]

In [49]:
print(X,Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [70]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30)

In [71]:
X_train, X_dev, Y_train, Y_dev = train_test_split(X_train, Y_train, test_size=0.1)
print(X_train)
print(Y_train)

[[1.216e+01 1.803e+01 7.829e+01 ... 5.690e-02 2.406e-01 7.729e-02]
 [1.553e+01 3.356e+01 1.037e+02 ... 2.014e-01 3.512e-01 1.204e-01]
 [1.831e+01 2.058e+01 1.208e+02 ... 1.510e-01 3.074e-01 7.863e-02]
 ...
 [1.227e+01 2.997e+01 7.742e+01 ... 0.000e+00 2.409e-01 6.743e-02]
 [1.283e+01 1.573e+01 8.289e+01 ... 9.783e-02 3.006e-01 7.802e-02]
 [1.398e+01 1.962e+01 9.112e+01 ... 1.827e-01 3.179e-01 1.055e-01]]
[1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1
 1 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 0 1
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0
 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 0 1 0 1 1
 1 0 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 0 1 0 1 0 0
 1 1 1 0 1 0 0 0 1 1 1 0 0 1 1 0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 0 1
 1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 

In [105]:
print(X_train.shape)
print(X_dev.shape)
print(X_test.shape)


(30, 358)
(30, 40)
(171, 30)


In [86]:
import sklearn as sk
scaler=sk.preprocessing.MinMaxScaler()

In [87]:
for a in range(X_train.shape[1]):
  X_train[:,a]=scaler.fit_transform(X_train[:,a].reshape(-1, 1)).flatten()
  print(a)
  

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [ ]:
for i in range(len(Y_train)):
    print(Y_train[i])
    
    

In [77]:
Y_train=np.array(pd.get_dummies(np.array(Y_train)))
Y_dev=np.array(pd.get_dummies(np.array(Y_dev)))

In [78]:
Y_train.shape,Y_dev.shape

((358, 2), (40, 2))

In [79]:
print(Y_train)

[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]

In [80]:
X_train=np.transpose(X_train)
X_dev=np.transpose(X_dev)
Y_train=np.transpose(Y_train)
Y_dev=np.transpose(Y_dev)

In [81]:
X_train.shape,Y_train.shape

((30, 358), (2, 358))

In [132]:
numHidden1 = 5 # number of hidden nodes
numHidden2 = 5# number of hidden nodes
numHidden3 = 5# number of hidden nodes
numHidden4 = 5# number of hidden nodes
numHidden5 = 5# number of hidden nodes
numHidden6 = 5# number of hidden nodes
num_features = X_train.shape[0]
numOutput = 2
max_epoches = 1000000
alpha = 0.001
epsilon=0.0000001
NN = NeuralNet(num_features, numHidden1,numHidden2,numHidden3,numHidden4,numHidden5,numHidden6, alpha, max_epoches, numOutput,epsilon)

In [67]:
dir(NN)

['Bias_H1_to_H2',
 'Bias_H2_to_H3',
 'Bias_H3_to_H4',
 'Bias_H4_to_H5',
 'Bias_H5_to_H6',
 'Bias_H6_to_output',
 'Bias_Input_to_H1',
 'Softmax_grad',
 'Weights_H1_to_H2',
 'Weights_H2_to_H3',
 'Weights_H3_to_H4',
 'Weights_H4_to_H5',
 'Weights_H5_to_H6',
 'Weights_H6_to_output',
 'Weights_Input_to_H1',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'alpha',
 'backprop',
 'dBias_H1_to_H2',
 'dBias_H2_to_H3',
 'dBias_H3_to_H4',
 'dBias_H4_to_H5',
 'dBias_H5_to_H6',
 'dBias_H6_to_output',
 'dBias_Input_to_H1',
 'dWeights_H1_to_H2',
 'dWeights_H2_to_H3',
 'dWeights_H3_to_H4',
 'dWeights_H4_to_H5',
 'dWeights_H5_to_H6',
 'dWeights_H6_to_output',
 'dWeights_Input_to_H1',
 '

In [97]:
members = {("NN."+attr) for attr in dir(NN) if not callable(getattr(NN, attr)) and not attr.startswith("__")}


In [98]:
members

{'NN.Bias_H1_to_H2',
 'NN.Bias_H2_to_H3',
 'NN.Bias_H3_to_H4',
 'NN.Bias_H4_to_H5',
 'NN.Bias_H5_to_H6',
 'NN.Bias_H6_to_output',
 'NN.Bias_Input_to_H1',
 'NN.CCloss',
 'NN.Weights_H1_to_H2',
 'NN.Weights_H2_to_H3',
 'NN.Weights_H3_to_H4',
 'NN.Weights_H4_to_H5',
 'NN.Weights_H5_to_H6',
 'NN.Weights_H6_to_output',
 'NN.Weights_Input_to_H1',
 'NN.a1',
 'NN.a2',
 'NN.a3',
 'NN.a4',
 'NN.a5',
 'NN.a6',
 'NN.a7',
 'NN.alpha',
 'NN.dBias_H1_to_H2',
 'NN.dBias_H2_to_H3',
 'NN.dBias_H3_to_H4',
 'NN.dBias_H4_to_H5',
 'NN.dBias_H5_to_H6',
 'NN.dBias_H6_to_output',
 'NN.dBias_Input_to_H1',
 'NN.dWeights_H1_to_H2',
 'NN.dWeights_H2_to_H3',
 'NN.dWeights_H3_to_H4',
 'NN.dWeights_H4_to_H5',
 'NN.dWeights_H5_to_H6',
 'NN.dWeights_H6_to_output',
 'NN.dWeights_Input_to_H1',
 'NN.dz1',
 'NN.dz2',
 'NN.dz3',
 'NN.dz4',
 'NN.dz5',
 'NN.dz6',
 'NN.dz7',
 'NN.loss',
 'NN.max_epochs',
 'NN.num_features',
 'NN.num_hidden1',
 'NN.num_hidden2',
 'NN.num_hidden3',
 'NN.num_hidden4',
 'NN.num_hidden5',
 'NN.num_

In [99]:
dic={}

In [100]:
for i in members:
    try:
        dic[i]=eval(i).shape
    except:
        pass
        
    

In [101]:
dic
    

{'NN.z1': (500, 358),
 'NN.Weights_H5_to_H6': (500, 500),
 'NN.a5': (500, 358),
 'NN.Bias_H4_to_H5': (500, 1),
 'NN.Weights_H6_to_output': (2, 500),
 'NN.Bias_Input_to_H1': (500, 1),
 'NN.a1': (500, 358),
 'NN.z4': (500, 358),
 'NN.Bias_H1_to_H2': (500, 1),
 'NN.Bias_H6_to_output': (2, 1),
 'NN.dWeights_H2_to_H3': (500, 500),
 'NN.dBias_H2_to_H3': (500, 1),
 'NN.dBias_H5_to_H6': (500, 1),
 'NN.Weights_H4_to_H5': (500, 500),
 'NN.a4': (500, 358),
 'NN.dWeights_H4_to_H5': (500, 500),
 'NN.dWeights_Input_to_H1': (500, 30),
 'NN.dBias_H6_to_output': (2, 1),
 'NN.z6': (500, 358),
 'NN.dWeights_H5_to_H6': (500, 500),
 'NN.Bias_H2_to_H3': (500, 1),
 'NN.dz4': (500, 358),
 'NN.dBias_H4_to_H5': (500, 1),
 'NN.dz7': (2, 358),
 'NN.dBias_Input_to_H1': (500, 1),
 'NN.dz3': (500, 358),
 'NN.Bias_H3_to_H4': (500, 1),
 'NN.Weights_Input_to_H1': (500, 30),
 'NN.a3': (500, 358),
 'NN.CCloss': (),
 'NN.dWeights_H3_to_H4': (500, 500),
 'NN.dz1': (500, 358),
 'NN.dz5': (500, 358),
 'NN.dz6': (500, 358),
 

In [102]:
NN.loss

[1055.4053010781367,
 990.4685312623294,
 984.0906535506243,
 981.0977661982902,
 979.2719603906143,
 977.9604668079212,
 977.9882497007924,
 976.6713745731705,
 975.7775211123733,
 975.2059001425464,
 974.580739965045,
 974.1954906583907,
 973.8000308675845,
 973.4658598569606,
 973.1750348610234,
 972.9290660288522,
 972.7693870752452,
 972.5861663260093,
 972.403278149314,
 972.2656055783361,
 972.1432207964966,
 971.9738032419286,
 971.7965080002409,
 971.7351354168084,
 971.4995557670079,
 971.4366846766904,
 971.397888978711,
 971.3753623393108,
 971.3162796439331,
 971.2074218442012,
 971.1533652431594,
 971.0249696956846,
 971.0162434771096,
 970.9948693516047,
 970.868063480127,
 970.7120740152661,
 970.6188204988991,
 970.6068821462569,
 970.5308979337352,
 970.5518828292941,
 970.3999471478885,
 970.2277444536257,
 970.2914634958385,
 970.1286894106241,
 970.1011253900341,
 970.0110455195754,
 969.9654457816071,
 970.0014777969202,
 969.812554869546,
 969.8420926994218,
 969

In [92]:
for key,value in dic.items():
    try:
        print(key,value.shape)
    except:
        pass
    
        
        
    

In [89]:
NN.forward(X_train).shape

(4, 122553)

In [96]:
Y_train

array([[0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
        1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
        1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 

In [ ]:
(NN.Weights_H6_to_output)

In [ ]:
(np.dot(NN.dy,NN.Weights_H6_to_output)*(NN.deriv(NN.z6))).shape

In [127]:
NN.backprop(X_train,Y_train)

In [ ]:
NN.d

In [259]:
NN.z7.shape

(2, 80)

In [103]:
Y_train.T.shape

(4, 122553)

In [ ]:
np.dot(X_train.T,NN.dz1)

In [268]:
np.set_printoptions(precision=5)

In [82]:
print (NN.a7)

[[1.31224095e-08 2.31967200e-06 9.99888522e-01 5.93015539e-02
  9.99999937e-01 9.99833386e-01 1.48396418e-02 5.71529441e-05
  9.99992210e-01 5.50128327e-04 1.42403625e-01 1.66198914e-05
  9.99999995e-01 9.99999995e-01 6.44264144e-09 1.29044725e-01
  9.99995945e-01 1.81294141e-04 1.66723745e-02 9.99985941e-01
  1.04521375e-02 9.99999959e-01 9.99992584e-01 9.99945107e-01
  2.72418376e-02 4.29370957e-05 3.15047909e-02 9.99999026e-01
  7.94003347e-04 9.99999058e-01 9.99999062e-01 9.99888522e-01
  9.99996220e-01 9.99985338e-01 4.65804936e-07 1.42773619e-05
  6.29374828e-06 9.99998127e-01 9.99992584e-01 9.99999961e-01
  9.99999026e-01 1.00000000e+00 6.58410938e-05 6.29374828e-06
  9.99992471e-01 7.10075645e-03 8.16678601e-07 9.99996245e-01
  9.99998127e-01 9.99833386e-01 1.00000000e+00 9.99999816e-01
  9.99999472e-01 2.25885462e-03 3.06674374e-04 1.94657225e-05
  9.99999995e-01 9.99999959e-01 8.26793802e-03 3.48325713e-10
  1.22956840e-01 1.81294141e-04 3.31649220e-02 1.04521375e-02
  2.8581

In [56]:
np.sum(NN.a7,axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [65]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
NN.fit(X_train,Y_train,X_dev,Y_dev)
# predict on the test set

step: 176400,  loss: 30.645707296027708821384294424206018447875976562500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 176500,  loss: 30.644922842288007558408935437910258769989013671875000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 176600,  loss: 30.644138271004354834303740062750875949859619140625000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 176700,  loss: 30.643353582843118942946603056043386459350585937500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 176800,  loss: 30.642568776783505768435134086757898330688476562500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 1769

step: 180600,  loss: 30.612669693360331280018726829439401626586914062500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 180700,  loss: 30.611880591527821593444969039410352706909179687500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 180800,  loss: 30.611091366491759657719740062020719051361083984375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 180900,  loss: 30.610302018016565028801778680644929409027099609375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 181000,  loss: 30.609512546021338863511118688620626926422119140625000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 1811

step: 184800,  loss: 30.579428320631912185945111559703946113586425781250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 184900,  loss: 30.578634405182402389300477807410061359405517578125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 185000,  loss: 30.577840360632695393405811046250164508819580078125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 185100,  loss: 30.577046186848239273103899904526770114898681640625000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 185200,  loss: 30.576251883694762767618158250115811824798583984375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 1853

step: 189000,  loss: 30.545971194326156705756147857755422592163085937500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 189100,  loss: 30.545171743040949507985715172253549098968505859375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 189200,  loss: 30.544372157161770786615306860767304897308349609375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 189300,  loss: 30.543572436561010619016087730415165424346923828125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 189400,  loss: 30.542772581111307772516738623380661010742187500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 1895

step: 193200,  loss: 30.512276904523528031631940393708646297454833984375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 193300,  loss: 30.511471691893099489334417739883065223693847656250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 193400,  loss: 30.510666339417774395315063884481787681579589843750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 193500,  loss: 30.509860846975250581181171583011746406555175781250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 193600,  loss: 30.509055214443083769992881570942699909210205078125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 1937

step: 197400,  loss: 30.478336174755089160726129193790256977081298828125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 197500,  loss: 30.477525028573101195661365636624395847320556640625000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 197600,  loss: 30.476713745108323649901649332605302333831787109375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 197700,  loss: 30.475902316617176524005117244087159633636474609375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 197800,  loss: 30.475090742981777225395489949733018875122070312500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 1979

step: 201600,  loss: 30.444146169751668651315412716940045356750488281250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 201700,  loss: 30.443329211745343343409331282600760459899902343750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 201800,  loss: 30.442512103757380259594356175512075424194335937500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 201900,  loss: 30.441694845665452362482028547674417495727539062500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 202000,  loss: 30.440877437347957368274364853277802467346191406250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 2021

step: 205800,  loss: 30.409706728903568517807798343710601329803466796875000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 205900,  loss: 30.408883512401050808193758712150156497955322265625000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 206000,  loss: 30.408060141089528372049244353547692298889160156250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 206100,  loss: 30.407236614858611289946566103026270866394042968750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 206200,  loss: 30.406412933598243597543842042796313762664794921875000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 2063

step: 210000,  loss: 30.375001014091147055751207517459988594055175781250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 210100,  loss: 30.374171409151649925206584157422184944152832031250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 210200,  loss: 30.373341644820175844188270275481045246124267578125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 210300,  loss: 30.372511720990271300024687661789357662200927734375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 210400,  loss: 30.371681637556005028955041780136525630950927734375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 2105

step: 214200,  loss: 30.340021314934720209066654206253588199615478515625000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 214300,  loss: 30.339185067097528047952437191270291805267333984375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 214400,  loss: 30.338348655429015821027860511094331741333007812500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 214500,  loss: 30.337512079827057220882124966010451316833496093750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 214600,  loss: 30.336675340189625416087437770329415798187255859375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0.9329608938547486
0.6
step: 2147

In [17]:
Y_pred = NN.predict(X_test.T)
Y_pred=np.where(Y_pred>0.5,1,0)
print("accuracy is {:1.3f}".format(accuracy_score(Y_test.T.astype(int), Y_pred)))

ValueError: Found input variables with inconsistent numbers of samples: [15, 3]

In [34]:
Y_pred = NN.forward(np.transpose(X_test))
#Y_pred=np.where(Y_pred>0.5,1,0)
print("accuracy is {:1.3f}".format(accuracy_score(np.argmax(np.transpose(Y_test).astype(int),axis=0), np.argmax(Y_pred,axis=0))))

accuracy is 0.133


In [48]:
Y_pred = NN.predict(X_train)
Y_pred=np.where(Y_pred>0.5,1,0)
print("accuracy is {:1.3f}".format(accuracy_score(Y_train.astype(int), Y_pred)))

ValueError: Classification metrics can't handle a mix of multilabel-indicator and binary targets

In [19]:
Y_test=np.array(pd.get_dummies(np.array(Y_test)))

In [ ]:
NN.backprop(X_train,Y_train)

In [55]:
### test cell ###
np.mean(np.argmax(Y_pred,axis=0)==np.argmax(np.transpose(Y_test).astype(int),axis=0))

0.5714285714285714

In [ ]:
NN.dWeights_H5_to_H6.shape

In [ ]:
sm(NN.y,axis=1)

In [ ]:
np.sum(NN.do*NN.Softmax_grad(NN.y),axis=0).shape

In [134]:
NN.alpha=0.0001

In [ ]:
NN.y[NN.y>0]=1

In [ ]:
NN.y

In [ ]:
NN.Weights_H5_to_H6

In [ ]:
np.matmul(np.transpose(NN.Weights_H6_to_output),np.transpose(NN.dy)).shape

In [ ]:
NN.dy.shape

In [ ]:
NN.dz6.shape

In [ ]:
NN.z6.shape

In [ ]:
self.Weights_H6_to_output

In [ ]:
np.transpose((np.matmul(np.transpose(NN.Weights_H5_to_H6),np.transpose(NN.dz6*NN.deriv(NN.z6))))).shape

In [ ]:
NN.dz5